(function(c){var g=function(c,a){var d=typeof c[a];return!!(/^function|object$/i.test(d)&&c[a]||d=="unknown")},e=document.createElement("input"),h={inputAttr:{placeholder:!!("placeholder"in e),required:!!("required"in e),pattern:!!("pattern"in e),min:!!("min"in e),max:!!("max"in e)},hostMethod:{validity:g(e,"validity"),checkValidity:g(e,"checkValidity"),setCustomValidity:g(e,"setCustomValidity"),valueAsNumber:g(e,"valueAsNumber"),valueAsDate:g(e,"valueAsDate")}},k=function(){if(h.inputAttr.placeholder)return function(a){a.get(0).control.value=
function(){return a.get(0).value}};var i=function(a,d){this.input=a;this.style=d.classes.placeholder;a.attr("type")=="password"&&this.handlePassword()};i.prototype={show:function(a){if(this.input[0].value===""||a&&this.valueIsPlaceholder()){if(this.isPassword)try{this.input[0].setAttribute("type","text")}catch(d){this.input.before(this.fakePassword.show()).hide()}this.input.addClass(this.style);this.input[0].value=this.input.attr(this.style)}},hide:function(){if(this.valueIsPlaceholder()&&this.input.hasClass(this.style)&&
(this.input.removeClass(this.style),this.input[0].value="",this.isPassword)){try{this.input[0].setAttribute("type","password")}catch(a){}this.input.show();this.input[0].focus()}},valueIsPlaceholder:function(){return this.input[0].value==this.input.attr(this.style)},handlePassword:function(){var a=this.input;a.attr("realType","password");this.isPassword=!0;if(c.browser.msie&&a[0].outerHTML){var d=c(a[0].outerHTML.replace(/type=(['"])?password\1/gi,"type=$1text$1"));this.fakePassword=d.val(a.attr(this.style)).addClass(this.style).focus(function(){a.trigger("focus");
c(this).hide()});c(a[0].form).submit(function(){d.remove();a.show()})}}};return function(a,d){var b=a.get(0);if(a.attr("placeholder")){b.control.value=function(){var b=a.attr("placeholder"),c=a.val();return b&&a.hasClass(d.classes.placeholder)&&c===b?"":c};var f=new i(a,d);f.show(!0);a.focus(function(){f.hide()}).blur(function(){f.show(!1)});c.browser.msie&&(c(window).load(function(){a.val()&&a.removeClass(d.classes.placeholder);f.show(!0)}),a.focus(function(){if(this.value==""){var a=this.createTextRange();
a.collapse(!0);a.moveStart("character",0);a.select()}}))}else b.control.value=function(){return b.value}}}(),l=function(){if(h.hostMethod.validity)return function(){};var i={email:/^[a-z0-9_.%+-]+@[0-9a-z.-]+\.[a-z.]{2,6}$/i,url:/[a-z][-.+a-z]*:\/\//i};return function(a,d){var b=a.get(0),f=b.getAttribute("type");b.validationMessage="";b.validity={customError:!1,patternMismatch:!1,rangeOverflow:!1,rangeUnderflow:!1,stepMismatch:!1,tooLong:!1,typeMismatch:!1,valid:!0,valueMissing:!1};a.attr("required")!==
void 0&&a.addClass(d.classes.required);for(var e=[{check:!0,op:function(){if(b.validity.customError)return b.validationMessage}},{check:a.attr("required")!==void 0,op:function(){if(b.control.value()==="")return b.validity.valueMissing=!0,d.messages.required;else b.validity.valueMissing=!1}},{check:f==="email"||f==="url",op:function(){var a=b.control.value();if(!i[f].test(a)&&a!=="")return b.validity.typeMismatch=!0,d.messages[f];else b.validity.typeMismatch=!1}},{check:f==="number",op:function(){var a=
b.control.value();if(isNaN(a)&&a!=="")return b.validity.typeMismatch=!0,d.messages.number;else b.validity.typeMismatch=!1}},{check:a.attr("pattern")!==void 0,op:function(){var c=b.control.value();if(!RegExp(a.attr("pattern")).test(c)&&c!=="")return b.validity.patternMismatch=!0,d.messages.pattern;else b.validity.patternMismatch=!1}}],g=[],j=0;j<e.length;j++)e[j].check&&g.push(e[j].op);e=b.control.validate=function(){for(var c=void 0,f=0;f<g.length;f++){var e=g[f]();e&&!c&&(c=e)}b.validationMessage=
c||"";b.validity.valid=!b.validity.customError&&!b.validity.valueMissing&&!b.validity.tooLong&&!b.validity.typeMismatch&&!b.validity.patternMismatch&&!b.validity.rangeOverflow&&!b.validity.rangeUnderflow&&!b.validity.stepMismatch;b.validity.valid?a.removeClass(d.classes.invalid).addClass(d.classes.valid):a.removeClass(d.classes.valid).addClass(d.classes.invalid)};c.browser.msie&&a.bind("keyup change",function(){c(this).trigger("input")});a.bind("input change",e);b.control.validate();if(!h.hostMethod.setCustomValidity)b.setCustomValidity=
function(a){b.validity.customError=!!a;b.validationMessage=a||"";b.control.validate()};if(!h.hostMethod.checkValidity)b.checkValidity=function(){var c=!!b.validity&&b.validity.valid;a.trigger(c?"valid":"invalid");return c}}}(),m=function(e,a){if(!h.hostMethod.validity||a.error.force)e.get(0).control.error=a.error.create.apply(e),e.bind("invalid",function(){c(this.control.error).text(this.validationMessage)}),c.browser.msie&&e.bind("valid",function(){c(this.control.error).text("")}).bind("focus",function(){c(this.control.error).show()}).bind("blur",
function(){c(this.control.error).hide()})};c.fn.f5=function(e){var a={classes:{valid:"valid",invalid:"invalid",required:"required",placeholder:"placeholder"},messages:{required:"Please fill out this field.",pattern:"Please match the requested format.",email:"Please enter an email address.",url:"Please enter URL",number:"Please enter numeric value",max:"Value too large",min:"Value too small"},error:{force:!1,create:function(){var a=c('<span class="error"></span>');c(this).after(a);return a}}};e&&c.extend(!0,
a,e);return this.filter("form").each(function(){var d=c(this);c(":input:not(:submit):not(:reset)",d).each(function(){var b=c(this);b.get(0).control={};k(b,a);m(b,a);l(b,a)});var b=g(d.get(0),"checkValidity");if(!b)d.get(0).checkValidity=function(){c(":input:not(:submit):not(:reset)",d).each(function(){c(this).get(0).checkValidity()||(all=!1)});return all};b||d.bind("submit",function(){var a=c(":input:not(:submit):not(:reset)",d).filter(function(){return!c(this).get(0).validity.valid});return a.length==
0?(c(":input:not(:submit):not(:reset)",d).each(function(){$this=c(this);$this.val($this.get(0).control.value())}),!0):(d.get(0).checkValidity(),a.filter(":first").select(),!1)})})}})(jQuery);